### ISSUE TITLE
Import does not work

### ISSUE THREAD

**Issue by AngelGordillo** [hpuhr/COMPASS#271]
Hi there,
I´ve installed the last version of the app in a Ubuntu 20.04. I launch normally the app from the AppImage, so far so good.
The issue comes when I try to import an .ast file, the loading gets stuck just showing unknown numer of plots and the progress bar never grows.
Am I doing something wrong?
Thanks in advance
PD I used the newos image, the oldos does not open

**Comment by hpuhr** [comment]
Hi,
  thanks for the interest in COMPASS and the error report.

It could be either a previous bug (occurs with very small files, should be fixed in an upcoming release) or "wrong" decoder settings (wrong file framing or ASTERIX editions). But in both cases this should not happen - could you send me the .ast file and a screenshot of the used decoder settings to compass@openats.at? I'll delete the file immediately after testing.

Thank you, regards,
  Helmut

**Comment by hpuhr** [comment]
Issue report resolved - the problem was a combination of usage error (wrong framing during import) and a bug (application unresponsive after certain decoding errors). User was able to decode correctly with the right settings, and bug was already resolved in current source - to be released soon.
