### ISSUE TITLE
Framing items in database.

### ISSUE THREAD

**Issue by tomasgerat** [hpuhr/COMPASS#327]
Hello, i created custom framing for ff2 format. This format contains additional info like system receiving time of asterix message, which is outside asterix block. Is it possible to add this additional info to result database for each Cat48 item?
How Compass know that item "content" in framing definition containst asterix data block? What is Compass doing with other framing items, for example with start_datetime in rff.json framing?

**Comment by hpuhr** [comment]
Hello, apologies for the late reply. Unfortunately no, this is currently not possible - the framing information is currently not parsed in COMPASS - but technically it would be possible to add bit of coding+config changes. Would this be an important requirement to you? If so, please contact me by mail at compass@openats.at to discuss this further - I'll add a summary to this issue here later.

**Comment by hpuhr** [comment]
Closed after 6 weeks of non-reply by OP.
